WebApiSAmples/Models/Inputs.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace WebApiSAmples.Models
{
    public enum EnumType
    {
        [Description("Enum Value 1")]
        EnumValue1 = 1,
        [Description("Enum Value 2")]
        EnumValue2 = 2,
        [Description("Enum Value 3")]
        EnumValue3 = 3
    }
    
    public class Inputs
    {
        public bool BoolValue { get; set; }
        public DateTime DateValue { get; set; }

        [DisplayFormat(DataFormatString = "{0:C}", ApplyFormatInEditMode = true)]
        public Decimal DecimalValue { get; set; }

        [UIHint("Enum")]
        public EnumType EnumValue { get; set; }

        public HttpPostedFileBase FileValue { get; set; }
        public int IntValue { get; set; }
        public string MarkdownValue { get; set; }
        public string LongTextValue { get; set; }
        public string PasswordValue { get; set; }
        public float FloatValue { get; set; }
        public string StringValue { get; set; }
        [EmailAddress]
        public string EmailValue { get; set; }

        [DisplayFormat(DataFormatString = "{0:hh\\:mm}", ApplyFormatInEditMode = true)]
        public TimeSpan TimeSpanValue { get; set; }
    }
}

WebApiSAmples/ViewModels/JobTitleDetail.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApiSAmples.ViewModels
{
    public class JobTitleDetail
    {
        [HiddenInput(DisplayValue = false)]
        public long Id { get; set; }

        [Required(ErrorMessage = "Job-title is required")]
        [StringLength(50, ErrorMessage = "Job-title must have at least 3 to 50 characters.", MinimumLength = 3)]
        public string Title { get; set; }


        [StringLength(100, ErrorMessage = "Description must have at least 10 to 100 characters", MinimumLength = 10)]
        public string Description { get; set; }

    }
}

WebApiSAmples/Controllers/BootstrapEditorTemplatesController.cs
using WebApiSAmples.Models;
using System.Web.Mvc;

namespace WebApiSAmples.Controllers
{
    public class BootstrapEditorTemplatesController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Inputs model)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Message = "All inputs are Valid!";
            }
            return View(model);
        }
    }
}

WebApiSAmples/Controllers/JobTitleController.cs
using CRM.DataAccessLayer.Interface;
using CRM.Model.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApiSAmples.ViewModels;

namespace WebApiSAmples.Controllers
{
    public class JobTitleController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public JobTitleController(IUnitOfWork unitOfWork)
        {
            this._unitOfWork = unitOfWork;
        }

        public ActionResult Index()
        {
            return View();
        }

        #region Basic CRUD


        [HttpGet]
        public ActionResult CreateNewJobTitle ()
        {
            JobTitleDetail jobTitleDetail = new JobTitleDetail();

            return View(jobTitleDetail);

        }

        [HttpPost]
        public ActionResult CreateNewJobTitle(JobTitleDetail jobTitle)
        {

            if (ModelState.IsValid)
            {
                this._unitOfWork.JobTitleRepository.Add(new JobTitle { });
                this._unitOfWork.Commit();
            }

            return View();
        }



        #endregion


    }
}

WebApiSAmples/Views/BootstrapEditorTemplates/Index.cshtml
@model WebApiSAmples.Models.Inputs

@{
    ViewBag.Title = "Inputs";
    Layout = "~/Views/Shared/_Layout.BootstrapEditorTemplates.cshtml";
}

<h1>@ViewBag.Title <small>test page for Bootstrap 3 EditorTemplates</small></h1>
@using (Html.BeginForm(null, null, null, FormMethod.Post, new { @class = "form-horizontal well" }))
{
        @Html.AntiForgeryToken()

        if (ViewBag.Message != null)
        {
            <div class="alert alert-success alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <strong>Ok!</strong> @ViewBag.Message
            </div>
        }

        @Html.ValidationSummary(true)

        <fieldset>
            <legend>Test all EditorTemplates</legend>
            <div class="container">

                @Html.EditorFor(m => m.BoolValue)
                @Html.EditorFor(m => m.DateValue)
                @Html.EditorFor(m => m.DecimalValue)
                @Html.EditorFor(m => m.EnumValue)
                @Html.EditorFor(m => m.FileValue)
                @Html.EditorFor(m => m.FloatValue)
                @Html.EditorFor(m => m.IntValue)
                @Html.EditorFor(m => m.LongTextValue, "Multiline")
                @Html.EditorFor(m => m.MarkdownValue, "Markdown")
                @Html.EditorFor(m => m.PasswordValue, "Password")
                @Html.EditorFor(m => m.StringValue)
                @Html.EditorFor(m => m.EmailValue)
                @Html.EditorFor(m => m.TimeSpanValue)

            </div>
            <input class="btn btn-primary" type="submit" value="Done" />

        </fieldset>
}

@section Scripts {
    @Scripts.Render("~/Scripts/val")
    @Scripts.Render("~/Scripts/md")
    <script>
        (function ($) {
            setTimeout(function () {
                $("div.alert").alert('close');
            }, 3000);
        })(jQuery);

    </script>
}

WebApiSAmples/Views/JobTitle/CreateNewJobTitle.cshtml
@model WebApiSAmples.ViewModels.JobTitleDetail
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateNewJobTitle</title>
</head>
<body>
    <div> 


        @Html.Partial("~/Views/JobTitle/NewJobTitleForm.cshtml", Model)

       </div>
</body>
</html>

WebApiSAmples/Views/JobTitle/NewJobTitleForm.cshtml
@model WebApiSAmples.ViewModels.JobTitleDetail

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>JobTitleDetail</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WebApiSAmples/Views/shared/EditorTemplates/Boolean.cshtml
@using WebApiSAmples.Utility
@model Boolean?

@{
    var htmlAttributes = new RouteValueDictionary();
    if (ViewBag.@class != null)
    {
        htmlAttributes.Add("class", ViewBag.@class);
    }
}


<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "" })
    <div class="controls">
        @Html.CheckBox(
            "",
            Model.HasValue && Model.Value,
            htmlAttributes)
        @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
    </div>
</div>

WebApiSAmples/Views/shared/EditorTemplates/DateTime.cshtml
@using WebApiSAmples.Utility
@model DateTime?

@{
    DateTime dt;
    if (Model.HasValue)
    {
        dt = (DateTime)Model;
    }
    else
    {
        dt = DateTime.Now;
    }
}

<div class="form-group@(Html.ValidationErrorFor(m => m, " error has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    @Html.TextBoxFor(m => m, new { @class="form-control datepicker", data_provide="datepicker", data_date_language="globalize", data_date=dt, data_date_format=System.Threading.Thread.CurrentThread.CurrentUICulture.DateTimeFormat.ShortDatePattern.Replace("M", "m"), data_date_today_highlight="true", data_date_today_btn="false" })
    @Html.ValidationMessageFor(m => m, null, new { @class="help-block" })
</div>

WebApiSAmples/Views/shared/EditorTemplates/Decimal.cshtml
@using WebApiSAmples.Utility
@model decimal?

<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="input-group">
        <span class="input-group-addon">&euro;</span>@Html.TextBox(
        "",
        Model == null ? "" : String.Format(System.Globalization.CultureInfo.CurrentCulture, "{0:F2}", ViewData.ModelMetadata.Model),
        ViewBag.ClearTextField == true ? new { @class = "form-control clear-text-field input-block-level" } : new { @class = "form-control input-block-level" })</span>
    </div>
    @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
</div>

WebApiSAmples/Views/shared/EditorTemplates/EmailAddress.cshtml
@using WebApiSAmples.Utility
@model object

@{
    var htmlAttributes = new RouteValueDictionary();
    if (ViewBag.@class != null)
    {
        htmlAttributes.Add("class", "form-control " + ViewBag.@class);
    }
    else
    {
        htmlAttributes.Add("class", "form-control");
    }
    if (ViewBag.@type != null)
    {
        htmlAttributes.Add("type", ViewBag.@type);
    }
    else
    {
        htmlAttributes.Add("type", "email");
    }
    if (ViewBag.placeholder != null)
    {
        htmlAttributes.Add("placeholder", ViewBag.placeholder);
    }
}

<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="controls">
        @Html.TextBox(
            "",
            ViewData.TemplateInfo.FormattedModelValue,
            htmlAttributes)
        @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
    </div>
</div>

WebApiSAmples/Views/shared/EditorTemplates/Enum.cshtml
@using WebApiSAmples.Utility
@model object


<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    @Html.EnumDropDownListFor(m => m, new { @class = "form-control" })
    @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
</div>

WebApiSAmples/Views/shared/EditorTemplates/HttpPostedFileBase.cshtml
@using WebApiSAmples.Utility

<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="control-group">
        <span class="btn btn-default btn-file">
            Upload<input type="File" name="@Html.IdFor(m => m)" id="@Html.IdFor(m => m)" class="btn-default btn-file" />
        </span>
    </div>
</div>

WebApiSAmples/Views/shared/EditorTemplates/Int32.cshtml
@using WebApiSAmples.Utility
@model int?

@{
    int i;
    if (!Model.HasValue)
    {
        i = 0;
    }
    else
    {
        i = Model.Value;
    }
    
    var htmlAttributes = new RouteValueDictionary();
    if (ViewBag.@class != null)
    {
        htmlAttributes.Add("class", "form-control " + ViewBag.@class);
    }
    else
    {
        htmlAttributes.Add("class", "form-control");
    }
       
    if (ViewBag.placeholder != null)
    {
        htmlAttributes.Add("placeholder", ViewBag.placeholder);
    }
}

<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="controls">
        @Html.TextBox(
            "",
            ViewData.TemplateInfo.FormattedModelValue,
            htmlAttributes)
        @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
    </div>
</div>

WebApiSAmples/Views/shared/EditorTemplates/Markdown.cshtml
@using WebApiSAmples.Utility
@model object

@{
    string guidID = Guid.NewGuid().ToString();
}

<link rel="stylesheet" type="text/css" href="/Scripts/mdd_styles.css" />
<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="mdd_toolbar"></div>
    @Html.TextAreaFor(
            m => m,
            8, 15,
            ViewBag.ClearTextField == true ? new { @class = "form-control mdd_editor clear-text-field", data_mdd_preview = "#" + guidID } : new { @class = "form-control mdd_editor", data_mdd_preview = "#" + guidID })
    @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
    <br />
    <label>Preview</label>
    <hr />
    <div class="mdd_preview" id="@guidID"></div>
    <hr />
</div>

WebApiSAmples/Views/shared/EditorTemplates/Multiline.cshtml
@using WebApiSAmples.Utility
@model object

<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="controls">
        @Html.TextAreaFor(
            m => m,
            8, 8,
            ViewBag.ClearTextField == true ? new { @class = "form-control input-block-level clear-text-field" } : new { @class = "form-control input-block-level" } )
        @Html.ValidationMessageFor(m => m, null,  new { @class = "help-block" })
    </div>
</div>

WebApiSAmples/Views/shared/EditorTemplates/Password.cshtml
@using WebApiSAmples.Utility
@model object

@{
    var htmlAttributes = new RouteValueDictionary();
    if (ViewBag.@class != null)
    {
        htmlAttributes.Add("class", "form-control " + ViewBag.@class);
    }
    else
    {
        htmlAttributes.Add("class", "form-control");
    }
}


<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="controls">
        @Html.Password(
            "",
            ViewData.TemplateInfo.FormattedModelValue,
            htmlAttributes)
        @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
    </div>
</div>

WebApiSAmples/Views/shared/EditorTemplates/Single.cshtml
@using WebApiSAmples.Utility
@model float?

@{
    float f;
    if (!Model.HasValue)
    {
        f = 0.0f;
    }
    else
    {
        f = Model.Value;
    }
}

<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="input-group">
        @Html.TextBox(
        "", f,
        ViewBag.ClearTextField == true ? new { @class = "form-control clear-text-field input-block-level" } : new { @class = "form-control input-block-level" })<span class="input-group-addon">0,00</span>
    </div>
    @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
</div>

WebApiSAmples/Views/shared/EditorTemplates/String.cshtml
@using WebApiSAmples.Utility
@model object

@{
    var htmlAttributes = new RouteValueDictionary();
    if (ViewBag.@class != null)
    {
        htmlAttributes.Add("class", "form-control " + ViewBag.@class);
    }
    else
    {
        htmlAttributes.Add("class", "form-control");
    }
    if (ViewBag.@type != null)
    {
        htmlAttributes.Add("type", ViewBag.@type);
    }
    if (ViewBag.placeholder != null)
    {
        htmlAttributes.Add("placeholder", ViewBag.placeholder);
    }
}

<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="controls">
        @Html.TextBox(
            "",
            ViewData.TemplateInfo.FormattedModelValue,
            htmlAttributes)
        @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
    </div>
</div>

WebApiSAmples/Views/shared/EditorTemplates/Text.cshtml
@using WebApiSAmples.Utility
@model object

<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="controls">
        @Html.TextBox(
            "",
            ViewData.TemplateInfo.FormattedModelValue,
            ViewBag.ClearTextField == true ? new { @class = "form-control clear-text-field input-block-level" } : new { @class = "form-control input-block-level" } )
        @Html.ValidationMessageFor(m => m, null, new { @class = "help-block" })
    </div>
</div>

WebApiSAmples/Views/shared/EditorTemplates/TimeSpan.cshtml
@using WebApiSAmples.Utility
@model TimeSpan?

@{
    TimeSpan ts;
    
    if (Model == null)
    {
        ts = TimeSpan.FromMinutes(10);
    }
    else
    {
        ts = Model.Value;
    }
     
}
<div class="form-group@(Html.ValidationErrorFor(m => m, " has-error"))">
    @Html.LabelFor(m => m, new { @class = "control-label" })
    <div class="controls">
        @Html.TextBoxFor(m => m, "hh\\:mm", new { @Value = ts.ToString("hh\\:mm"), @class="form-control timepicker", data_provide="timepicker", data_minute_step="5", data_show_meridian="false", data_disable_focus="true", data_template = "dropdown", data_default_time="value"  })
        @Html.ValidationMessageFor(m => m, null, new { @class="help-block" })
    </div>
</div>

WebApiSAmples/Views/shared/_Layout.BootstrapEditorTemplates.cshtml
@using WebApiSAmples.Utility
<!DOCTYPE html>
<html lang="@LocalizationHelper.Lang">
    <head>
        <meta charset="utf-8">
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        @RenderSection("meta", required: false)
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <link href="~/Content/site" rel="stylesheet">

        @Html.Partial("_html5shiv")

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="~/Content/ico/apple-touch-icon-57-precomposed.png">
        <link href="~/Content/ico/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    </head>
    <body>
        @Html.Partial("/Views/Shared/_NavBar.BootstrapEditorTemplates.cshtml")

        @RenderSection("featured", required: false)

        <div class="container">
            @RenderBody()
            <hr />
            <div class="footer">
                <p>&copy; Company 2013</p>
            </div>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/Scripts/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

WebApiSAmples/Views/shared/_NavBar.BootstrapEditorTemplates.cshtml
@helper ActiveItem(string actionName, string controllerName, string areaName)
{
    if (ViewContext.RouteData.Values["action"].ToString() == actionName &&
            ViewContext.RouteData.Values["controller"].ToString() == controllerName &&
            (ViewContext.RouteData.DataTokens["area"] == null || ViewContext.RouteData.DataTokens["area"].ToString() == areaName))
    {
        @:active
    }
}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Sample Site</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="@ActiveItem("Index", "Home", null)">@Html.ActionLink("Home", "Index", "Home")</li>
                <li class="@ActiveItem("Index", "BoostrapEditorTemplates", null)">@Html.ActionLink("EditorTemplates", "Index", "BootstrapEditorTemplates")</li>
            </ul>
        </div>
    </div>
</div>

WebApiSAmples/Views/shared/_html5shiv.cshtml
   <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="~/scripts/html5.js"></script>
    <![endif]-->